### ISSUE TITLE
R6 classes use generator object names and not classname

### ISSUE THREAD

**Issue by jayqi** [jameslamb/rsixygen#14]
The `classname` that gets passed in to `R6::R6Class` is not required at all and does not have to match the name of the generator. The name of the generator is what is specified when defining a child class with inheritance. Additionally, a user would actually use the generator name to create a new object of that class. 

While there is a common convention to use the same name for both, we should change the it to use the generator object name. This matters in two places:
- The name that it writes the output file with
- The names of parent classes in the inheritance section of the roxygen skeleton

**Comment by jayqi** [comment]
Well, that's annoying. `Addresses` is not one of the triggering keywords.

**Comment by jameslamb** [comment]
oh wow I just noticed. Yeah very annoying.

hey @jayqi I want to add you as a `ctb` in the DESCRIPTION file. What email do you want me to use?

**Comment by jayqi** [comment]
Either my work email, or no email. @jameslamb

**Comment by jameslamb** [comment]
sounds good @jayqi . I went with "no email": https://github.com/jameslamb/rsixygen/commit/4d648aca6456f52301f2635ef3df41937cad40d3
