### ISSUE TITLE
R6 is now supported in Roxygen

### ISSUE THREAD

**Issue by VPetukhov** [jameslamb/rsixygen#26]
Hi! Thank you for the package! Fortunately, in v7 Roxygen added [support for R6 classes](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html). Perhaps, it at least worth mentioning in the readme.

**Comment by jameslamb** [comment]
@VPetukhov yep I agree!  You are totally right. I'd like to update the README here to point to that, and then archive this project.

This project helped me but I think putting my effort into the new "official" way in `roxygen2` is a better and higher-impact use of time.

Thanks for reminding me 😄

**Comment by jameslamb** [comment]
added #27 , thanks @VPetukhov
