### ISSUE TITLE
Add a pkgdown site

### ISSUE THREAD

**Issue by jameslamb** [jameslamb/rsixygen#8]
You should add a pkdown site and host it on github-pages

**Comment by BruceZhaoR** [comment]
I can contribute a PR to build pkgdown site

see demo : 
- build site <https://github.com/BruceZhaoR/lightgbm_r/blob/master/pkgdown/build-site.R>
- deploy <https://github.com/BruceZhaoR/lightgbm_r/blob/master/pkgdown/deploy.sh>
- and AppVeyor <https://github.com/BruceZhaoR/lightgbm_r/blob/master/appveyor.yml>

you need to set your GITHUB_PAT <https://happygitwithr.com/github-pat.html> to your AppVeyor environment, and the PR will work.

**Comment by jameslamb** [comment]
@BruceZhaoR whoa cool!!!! This is a really awesome idea. For some reason I thought GitHub discontinued the "you can host your pkgdown site on a `gh-pages` branch" thing, but looks like they did not.

Yes I would welcome a PR to add this approach for this package. We've gone back and forth on how to do it in some of the `UptakeOpenSource` projects (like `pkgnet`) as well! Right now on `pkgnet` we build locally and then check all the pkgdown files into `master` (https://github.com/UptakeOpenSource/pkgnet/tree/master/docs) which is not ideal.

I would love if you made a PR like this onto this `rsixygen` as a start. I can get my GITHUB_PAT up into AppVeyor this weekend (been meaning to learn it anyway).

**Comment by BruceZhaoR** [comment]
you need to checkout an orphan `gh-pages` branch.

```bash
git checkout --orphan gh-pages
git rm -rf *
touch .nojekyll
git add --all *
git commit -m "Initial commit"
git push -u origin gh-pages
```
@jameslamb  when you are ready please notify me.

**Comment by BruceZhaoR** [comment]
done! preview here: <https://brucezhaor.github.io/rsixygen/index.html>

code : https://github.com/BruceZhaoR/rsixygen

@jameslamb when you are ready please notify me, I will modify the `pkgdown/deploy.sh` and send a PR.

**Comment by jameslamb** [comment]
THIS IS SO COOL. Thanks for teaching me @BruceZhaoR !

I just made the orphaned `gh-pages` branch per your instructions and pushed it. Feel free to make a PR.

Really appreciate you taking the time to teach me and contribute here!
